import csv
from pathlib import Path

from build_promptfoo_tests import (
    contradiction_rubric,
    direct_answer_rubric,
    factuality_assertion,
    source_grounding_rubric,
    special_case_assertions,
    uncertainty_rubric,
    yaml_string,
)


ROOT = Path(__file__).resolve().parents[1]
QUESTIONS_CSV = ROOT / "scripts" / "r1_project_questions.csv"
GOLD_CONTEXTS_CSV = ROOT / "scripts" / "r1_project_gold_contexts.csv"
TESTS_YAML = ROOT / "scripts" / "promptfoo_gold_tests.yaml"
DEV_TESTS_YAML = ROOT / "scripts" / "promptfoo_gold_tests.dev.yaml"
HOLDOUT_TESTS_YAML = ROOT / "scripts" / "promptfoo_gold_tests.holdout.yaml"
DEV_SET_SIZE = 40


def read_gold_contexts() -> dict[str, str]:
    with GOLD_CONTEXTS_CSV.open(newline="", encoding="utf-8") as f:
        return {
            row["id"].strip(): row["gold_context"].strip()
            for row in csv.DictReader(f)
        }


def test_case(row: dict[str, str], gold_context: str) -> list[str]:
    question_id = row["id"].strip()
    question_type = row["type"].strip()
    question = row["question"].strip()
    answer = row["answer"].strip()

    lines = [
        f"- description: {yaml_string(f'{question_id}: {question}')}",
        "  vars:",
        f"    question: {yaml_string(question)}",
        f"    gold_context: {yaml_string(gold_context)}",
        "  metadata:",
        f"    id: {yaml_string(question_id)}",
        f"    type: {yaml_string(question_type)}",
        '    eval_mode: "gold_context"',
        "  threshold: 0.75",
        "  assert:",
    ]

    assertions: list[str] = []
    assertions.extend(factuality_assertion(answer))
    assertions.extend(contradiction_rubric(answer))
    assertions.extend(direct_answer_rubric(question_type, answer))
    assertions.extend(source_grounding_rubric())
    assertions.extend(uncertainty_rubric())
    assertions.extend(special_case_assertions(question, answer))

    lines.extend(f"  {line}" for line in assertions)
    return lines


def write_tests(rows: list[dict[str, str]], gold_contexts: dict[str, str], output_path: Path) -> None:
    output = [
        "# Generated by scripts/build_promptfoo_gold_tests.py.",
        "# Edit r1_project_questions.csv, r1_project_gold_contexts.csv, or this generator, then rerun.",
        "",
    ]

    for row in rows:
        output.extend(test_case(row, gold_contexts[row["id"].strip()]))

    output_path.write_text("\n".join(output) + "\n", encoding="utf-8")
    print(f"Wrote {len(rows)} gold-context promptfoo tests to {output_path}")


def main() -> None:
    with QUESTIONS_CSV.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    gold_contexts = read_gold_contexts()
    missing = [row["id"] for row in rows if row["id"].strip() not in gold_contexts]
    if missing:
        raise RuntimeError(f"Missing gold contexts for question ids: {', '.join(missing)}")

    dev_rows = rows[:DEV_SET_SIZE]
    holdout_rows = rows[DEV_SET_SIZE:]

    write_tests(rows, gold_contexts, TESTS_YAML)
    write_tests(dev_rows, gold_contexts, DEV_TESTS_YAML)
    write_tests(holdout_rows, gold_contexts, HOLDOUT_TESTS_YAML)


if __name__ == "__main__":
    main()
